---
- name: "mkdir ApacheKafka --> download and unzip Apache Kafka"
  hosts: "all"
  become: true

  tasks:
  - name: "1/3 apt update"
    apt:
      update_cache: yes

  - name: "2/3 mkdir ApacheKafka"
    file:
      path: /home/tverdyakov/ApacheKafka
      state: directory

  - name: "3/3 Download and unzip Apache Kafka"
    unarchive:
      src: "https://downloads.apache.org/kafka/3.7.0/kafka-3.7.0-src.tgz"
      dest: /home/tverdyakov/ApacheKafka
      remote_src: yes
